package io.github.goquati.kotlin.util

public sealed class QuatiException(
    public val status: Int,
    public val msg: String,
    throwable: Throwable? = null,
) : RuntimeException(msg, throwable) {
    public companion object {
        public fun ofOrNull(status: Int, msg: String, t: Throwable? = null): QuatiException? = when (status) {
            400 -> BadRequest(msg, t)
            401 -> Unauthorized(msg, t)
            402 -> PaymentRequired(msg, t)
            403 -> Forbidden(msg, t)
            404 -> NotFound(msg, t)
            405 -> MethodNotAllowed(msg, t)
            406 -> NotAcceptable(msg, t)
            407 -> ProxyAuthenticationRequired(msg, t)
            408 -> RequestTimeout(msg, t)
            409 -> Conflict(msg, t)
            410 -> Gone(msg, t)
            411 -> LengthRequired(msg, t)
            412 -> PreconditionFailed(msg, t)
            413 -> PayloadTooLarge(msg, t)
            414 -> UriTooLong(msg, t)
            415 -> UnsupportedMediaType(msg, t)
            416 -> RequestedRangeNotSatisfiable(msg, t)
            417 -> ExpectationFailed(msg, t)
            418 -> IAmATeapot(msg, t)
            422 -> UnprocessableEntity(msg, t)
            423 -> Locked(msg, t)
            424 -> FailedDependency(msg, t)
            425 -> TooEarly(msg, t)
            426 -> UpgradeRequired(msg, t)
            428 -> PreconditionRequired(msg, t)
            429 -> TooManyRequests(msg, t)
            431 -> RequestHeaderFieldsTooLarge(msg, t)
            451 -> UnavailableForLegalReasons(msg, t)
            500 -> InternalServerError(msg, t)
            501 -> NotImplemented(msg, t)
            502 -> BadGateway(msg, t)
            503 -> ServiceUnavailable(msg, t)
            504 -> GatewayTimeout(msg, t)
            505 -> HttpVersionNotSupported(msg, t)
            506 -> VariantAlsoNegotiates(msg, t)
            507 -> InsufficientStorage(msg, t)
            508 -> LoopDetected(msg, t)
            509 -> BandwidthLimitExceeded(msg, t)
            510 -> NotExtended(msg, t)
            511 -> NetworkAuthenticationRequired(msg, t)
            else -> null
        }
    }

    public class BadRequest(msg: String, t: Throwable? = null) : QuatiException(400, msg, t)
    public class Unauthorized(msg: String, t: Throwable? = null) : QuatiException(401, msg, t)
    public class PaymentRequired(msg: String, t: Throwable? = null) : QuatiException(402, msg, t)
    public class Forbidden(msg: String, t: Throwable? = null) : QuatiException(403, msg, t)
    public class NotFound(msg: String, t: Throwable? = null) : QuatiException(404, msg, t)
    public class MethodNotAllowed(msg: String, t: Throwable? = null) : QuatiException(405, msg, t)
    public class NotAcceptable(msg: String, t: Throwable? = null) : QuatiException(406, msg, t)
    public class ProxyAuthenticationRequired(msg: String, t: Throwable? = null) : QuatiException(407, msg, t)
    public class RequestTimeout(msg: String, t: Throwable? = null) : QuatiException(408, msg, t)
    public class Conflict(msg: String, t: Throwable? = null) : QuatiException(409, msg, t)
    public class Gone(msg: String, t: Throwable? = null) : QuatiException(410, msg, t)
    public class LengthRequired(msg: String, t: Throwable? = null) : QuatiException(411, msg, t)
    public class PreconditionFailed(msg: String, t: Throwable? = null) : QuatiException(412, msg, t)
    public class PayloadTooLarge(msg: String, t: Throwable? = null) : QuatiException(413, msg, t)
    public class UriTooLong(msg: String, t: Throwable? = null) : QuatiException(414, msg, t)
    public class UnsupportedMediaType(msg: String, t: Throwable? = null) : QuatiException(415, msg, t)
    public class RequestedRangeNotSatisfiable(msg: String, t: Throwable? = null) : QuatiException(416, msg, t)
    public class ExpectationFailed(msg: String, t: Throwable? = null) : QuatiException(417, msg, t)
    public class IAmATeapot(msg: String, t: Throwable? = null) : QuatiException(418, msg, t)
    public class UnprocessableEntity(msg: String, t: Throwable? = null) : QuatiException(422, msg, t)
    public class Locked(msg: String, t: Throwable? = null) : QuatiException(423, msg, t)
    public class FailedDependency(msg: String, t: Throwable? = null) : QuatiException(424, msg, t)
    public class TooEarly(msg: String, t: Throwable? = null) : QuatiException(425, msg, t)
    public class UpgradeRequired(msg: String, t: Throwable? = null) : QuatiException(426, msg, t)
    public class PreconditionRequired(msg: String, t: Throwable? = null) : QuatiException(428, msg, t)
    public class TooManyRequests(msg: String, t: Throwable? = null) : QuatiException(429, msg, t)
    public class RequestHeaderFieldsTooLarge(msg: String, t: Throwable? = null) : QuatiException(431, msg, t)
    public class UnavailableForLegalReasons(msg: String, t: Throwable? = null) : QuatiException(451, msg, t)
    public class InternalServerError(msg: String, t: Throwable? = null) : QuatiException(500, msg, t)
    public class NotImplemented(msg: String, t: Throwable? = null) : QuatiException(501, msg, t)
    public class BadGateway(msg: String, t: Throwable? = null) : QuatiException(502, msg, t)
    public class ServiceUnavailable(msg: String, t: Throwable? = null) : QuatiException(503, msg, t)
    public class GatewayTimeout(msg: String, t: Throwable? = null) : QuatiException(504, msg, t)
    public class HttpVersionNotSupported(msg: String, t: Throwable? = null) : QuatiException(505, msg, t)
    public class VariantAlsoNegotiates(msg: String, t: Throwable? = null) : QuatiException(506, msg, t)
    public class InsufficientStorage(msg: String, t: Throwable? = null) : QuatiException(507, msg, t)
    public class LoopDetected(msg: String, t: Throwable? = null) : QuatiException(508, msg, t)
    public class BandwidthLimitExceeded(msg: String, t: Throwable? = null) : QuatiException(509, msg, t)
    public class NotExtended(msg: String, t: Throwable? = null) : QuatiException(510, msg, t)
    public class NetworkAuthenticationRequired(msg: String, t: Throwable? = null) : QuatiException(511, msg, t)
}