name: Check

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*'

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: check
        run: ./gradlew check
      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jsBrowserTest-report
          path: kotlin-util-coroutine/build/reports/tests/allTests/
